### ISSUE TITLE
Ch01 Replace Figure caption repressor/activator

### ISSUE THREAD

**Issue by uliebal** [biocircuits/biocircuits.github.io#1]
Super instructive and engaging material. I have a tiny suggestion for the caption of the last figure in ch01. ` Introduction to biological circuit design`:
The `repressor` in the current text should be replaced by `activator` as the figure implies an activating factor.

**Comment by justinbois** [comment]
Thanks for spotting this! This has been corrected and will be updated in the next build (which may be in a few weeks).
